"""Migration 001: schemas, identity, patient record, audit log.

Written by hand rather than autogenerated. Autogenerate does not emit schema creation,
native enum types, partial indexes or role grants - and three of the constraints in this
migration are the ones the system's integrity actually rests on, so they should be
explicit and reviewable rather than inferred.

Scope is deliberately limited to what authentication and patient registration need.
Slots, appointments, encounters and the AI tables land in later migrations.

Revision ID: 0001
Revises:
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SCHEMAS = ("identity", "clinical", "operational", "ai", "audit", "analytics")


def upgrade() -> None:
    # --- Schemas -------------------------------------------------------------
    # Clinical/operational data is kept apart from analytics workloads so a heavy
    # report cannot contend with live booking (Analysis Report §8).
    for schema in SCHEMAS:
        op.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}"')

    # gen_random_uuid() for server-side defaults; btree_gist is needed in migration 002
    # for the clinician no-overlap exclusion constraint.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # --- Enums ---------------------------------------------------------------
    user_role = postgresql.ENUM(
        "PATIENT", "NURSE", "DOCTOR", "ADMIN", name="user_role", schema="identity"
    )
    user_role.create(op.get_bind(), checkfirst=True)

    user_status = postgresql.ENUM(
        "ACTIVE", "LOCKED", "DISABLED", name="user_status", schema="identity"
    )
    user_status.create(op.get_bind(), checkfirst=True)

    audit_result = postgresql.ENUM(
        "SUCCESS", "DENIED", "ERROR", name="audit_result", schema="audit"
    )
    audit_result.create(op.get_bind(), checkfirst=True)

    role_ref = postgresql.ENUM(name="user_role", schema="identity", create_type=False)
    status_ref = postgresql.ENUM(name="user_status", schema="identity", create_type=False)
    result_ref = postgresql.ENUM(name="audit_result", schema="audit", create_type=False)

    # --- identity.users ------------------------------------------------------
    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", role_ref, nullable=False),
        sa.Column("status", status_ref, nullable=False, server_default="ACTIVE"),
        sa.Column("failed_logins", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("locked_until", sa.DateTime(timezone=True)),
        sa.Column("last_login_at", sa.DateTime(timezone=True)),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema="identity",
    )
    # Case-insensitive uniqueness. Without this, Alex@example.test and alex@example.test
    # are two accounts, and a user who signs up twice cannot log in reliably.
    op.execute("CREATE UNIQUE INDEX uq_users_email_lower ON identity.users (lower(email))")

    # --- identity.refresh_tokens --------------------------------------------
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identity.users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        # The plaintext token is returned to the client once and never stored. A database
        # dump therefore does not yield usable sessions.
        sa.Column("token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True)),
        sa.Column(
            "replaced_by",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identity.refresh_tokens.id", ondelete="SET NULL"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema="identity",
    )
    op.create_index(
        "ix_refresh_tokens_active_user",
        "refresh_tokens",
        ["user_id"],
        schema="identity",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )

    # --- identity.password_reset_tokens -------------------------------------
    op.create_table(
        "password_reset_tokens",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identity.users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(64), nullable=False, unique=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True)),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema="identity",
    )

    # --- operational.sites / departments -------------------------------------
    op.create_table(
        "sites",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("code", sa.String(20), nullable=False, unique=True),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("address_line1", sa.String(200)),
        sa.Column("city", sa.String(100)),
        sa.Column("postcode", sa.String(10)),
        sa.Column("data_origin", sa.String(20), nullable=False, server_default="SYNTHETIC"),
        schema="operational",
    )
    op.create_table(
        "departments",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "site_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("operational.sites.id"),
            nullable=False,
        ),
        sa.Column("code", sa.String(20), nullable=False, unique=True),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("specialty_snomed", sa.String(20)),
        sa.Column("data_origin", sa.String(20), nullable=False, server_default="SYNTHETIC"),
        schema="operational",
    )

    # --- clinical.patients ---------------------------------------------------
    op.create_table(
        "patients",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identity.users.id"),
            unique=True,
        ),
        sa.Column("nhs_number", sa.String(10), unique=True),
        sa.Column("given_name", sa.String(100), nullable=False),
        sa.Column("family_name", sa.String(100), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("sex_at_birth", sa.String(30)),
        sa.Column("gender_identity", sa.String(60)),
        sa.Column("phone_e164", sa.String(20)),
        sa.Column("email", sa.String(320)),
        sa.Column("address_line1", sa.String(200)),
        sa.Column("address_line2", sa.String(200)),
        sa.Column("city", sa.String(100)),
        sa.Column("postcode", sa.String(10)),
        sa.Column("preferred_language", sa.String(10), nullable=False, server_default="en-GB"),
        sa.Column(
            "interpreter_needed", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        sa.Column("accessibility_needs", postgresql.ARRAY(sa.String(60))),
        sa.Column("data_origin", sa.String(20), nullable=False, server_default="SYNTHETIC"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        # Format only. Modulus 11 validity is enforced in the application, because a
        # checksum is not expressible as a simple CHECK constraint.
        sa.CheckConstraint(
            "nhs_number IS NULL OR nhs_number ~ '^[0-9]{10}$'",
            name="ck_patient_nhs_number_format",
        ),
        schema="clinical",
    )
    op.create_index(
        "ix_patients_name_dob",
        "patients",
        ["family_name", "date_of_birth"],
        schema="clinical",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # --- identity.staff ------------------------------------------------------
    op.create_table(
        "staff",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identity.users.id"),
            nullable=False,
            unique=True,
        ),
        sa.Column("staff_code", sa.String(32), nullable=False, unique=True),
        sa.Column("given_name", sa.String(100), nullable=False),
        sa.Column("family_name", sa.String(100), nullable=False),
        sa.Column("job_title", sa.String(120), nullable=False),
        sa.Column(
            "department_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("operational.departments.id"),
        ),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("data_origin", sa.String(20), nullable=False, server_default="SYNTHETIC"),
        schema="identity",
    )

    # --- identity.care_assignments ------------------------------------------
    op.create_table(
        "care_assignments",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "staff_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identity.staff.id"),
            nullable=False,
        ),
        sa.Column(
            "patient_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clinical.patients.id"),
            nullable=False,
        ),
        sa.Column(
            "department_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("operational.departments.id"),
        ),
        sa.Column(
            "valid_from",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("valid_to", sa.DateTime(timezone=True)),
        sa.Column("reason", sa.Text()),
        schema="identity",
    )
    op.create_index(
        "uq_care_assignment_active",
        "care_assignments",
        ["staff_id", "patient_id"],
        unique=True,
        schema="identity",
        postgresql_where=sa.text("valid_to IS NULL"),
    )

    # --- identity.breakglass_grants -----------------------------------------
    op.create_table(
        "breakglass_grants",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "staff_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("identity.staff.id"),
            nullable=False,
        ),
        sa.Column(
            "patient_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("clinical.patients.id"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        # A justification of "urgent" is not a justification. Enforced in the database so
        # it cannot be bypassed by a future code path that forgets to check.
        sa.CheckConstraint("length(trim(reason)) >= 20", name="ck_breakglass_reason_length"),
        schema="identity",
    )

    # --- audit.audit_logs ----------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True)),
        sa.Column("actor_role", role_ref),
        sa.Column("action", sa.String(60), nullable=False),
        sa.Column("resource_type", sa.String(60)),
        sa.Column("resource_id", postgresql.UUID(as_uuid=True)),
        sa.Column("result", result_ref, nullable=False),
        sa.Column("request_id", sa.String(64)),
        sa.Column("ip_hash", sa.String(64)),
        sa.Column("user_agent_hash", sa.String(64)),
        sa.Column(
            "metadata", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("detail", sa.Text()),
        schema="audit",
    )
    op.create_index(
        "ix_audit_resource",
        "audit_logs",
        ["resource_type", "resource_id", "occurred_at"],
        schema="audit",
    )
    op.create_index(
        "ix_audit_actor", "audit_logs", ["actor_user_id", "occurred_at"], schema="audit"
    )
    op.create_index("ix_audit_action", "audit_logs", ["action", "occurred_at"], schema="audit")

    # Append-only, enforced by trigger.
    #
    # A REVOKE was tried first and silently did nothing: the application connects as the
    # table's owner, and a Postgres owner keeps its privileges implicitly and can re-grant
    # them at will. The audit log was fully mutable while appearing to be protected, which
    # is worse than no protection, because the guarantee was documented and believed.
    #
    # A trigger holds regardless of ownership. Defeating it requires a deliberate
    # ALTER TABLE ... DISABLE TRIGGER - an explicit, visible act, not something reachable
    # through ordinary application code or an injected statement.
    #
    # Production hardening beyond this project's scope: connect the application as a
    # non-owner role holding only INSERT and SELECT here, so the two controls are
    # independent. Recorded in docs/security/rbac-and-audit.md.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit.prevent_audit_mutation() RETURNS trigger AS $fn$
        BEGIN
            RAISE EXCEPTION 'audit.audit_logs is append-only (attempted %)', TG_OP
                USING ERRCODE = 'insufficient_privilege';
        END
        $fn$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_audit_append_only
            BEFORE UPDATE OR DELETE ON audit.audit_logs
            FOR EACH ROW EXECUTE FUNCTION audit.prevent_audit_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_audit_append_only ON audit.audit_logs")
    op.execute("DROP FUNCTION IF EXISTS audit.prevent_audit_mutation()")
    op.drop_table("audit_logs", schema="audit")
    op.drop_table("breakglass_grants", schema="identity")
    op.drop_table("care_assignments", schema="identity")
    op.drop_table("staff", schema="identity")
    op.drop_index("ix_patients_name_dob", table_name="patients", schema="clinical")
    op.drop_table("patients", schema="clinical")
    op.drop_table("departments", schema="operational")
    op.drop_table("sites", schema="operational")
    op.drop_table("password_reset_tokens", schema="identity")
    op.drop_table("refresh_tokens", schema="identity")
    op.execute("DROP INDEX IF EXISTS identity.uq_users_email_lower")
    op.drop_table("users", schema="identity")

    op.execute("DROP TYPE IF EXISTS audit.audit_result")
    op.execute("DROP TYPE IF EXISTS identity.user_status")
    op.execute("DROP TYPE IF EXISTS identity.user_role")

    for schema in reversed(SCHEMAS):
        op.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')
