"""Indexes added because a measurement showed they were missing.

Every index here was justified by an EXPLAIN against realistic volume (20,000 patients,
64,000 slots, 15,000 appointments, generated by scripts/load_volume.py), not by guessing at
what might be slow. The two plans that showed a sequential scan on a table that grows
without bound are fixed; everything else already used an index and was left alone.

Full findings: docs/performance/baseline.md

Revision ID: 0004
Revises: 0003
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- Patient search -------------------------------------------------------------
    #
    # The clinician search matches a name fragment anywhere in the name, because staff
    # search on what the patient said rather than on how the record was filed - "the
    # O'Neill admitted yesterday" is typed as `neill`. That means LIKE '%neill%', and a
    # leading wildcard makes a btree index unusable: ix_patients_name_dob exists and the
    # planner correctly ignored it, falling back to a sequential scan of every patient.
    #
    # Measured: Seq Scan, 11,111 rows examined, 9.3ms. Correct, and linear in the size of
    # the patient register - so it degrades exactly as the service succeeds.
    #
    # pg_trgm indexes the three-character substrings of a value, which is what makes an
    # unanchored LIKE indexable. It is a core contrib module, present in the standard
    # postgres image.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # Indexed on lower(...) to match the query, which lowercases both sides so that
    # searching "oneill" finds "O'Neill". An index on the raw column would not be used.
    op.execute(
        """
        CREATE INDEX ix_patients_family_name_trgm
        ON clinical.patients USING gin (lower(family_name) gin_trgm_ops)
        """
    )
    op.execute(
        """
        CREATE INDEX ix_patients_given_name_trgm
        ON clinical.patients USING gin (lower(given_name) gin_trgm_ops)
        """
    )

    # --- Audit trail ----------------------------------------------------------------
    #
    # The audit log is append-only and every access to patient data writes to it, so it is
    # the fastest-growing table in the system and the only one with no natural ceiling.
    # It carried indexes on actor, action and resource - the columns an investigation
    # filters by - but none on occurred_at, which is what the default view sorts by. At
    # 221 rows that is a 0.2ms sort nobody notices; at a year of real traffic it is a sort
    # of the entire table to return twenty-five rows.
    #
    # DESC matches the query's ORDER BY so the index can be read forwards and the sort
    # dropped entirely.
    op.execute(
        """
        CREATE INDEX ix_audit_occurred_at
        ON audit.audit_logs (occurred_at DESC)
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS audit.ix_audit_occurred_at")
    op.execute("DROP INDEX IF EXISTS clinical.ix_patients_given_name_trgm")
    op.execute("DROP INDEX IF EXISTS clinical.ix_patients_family_name_trgm")
    # pg_trgm is deliberately left installed: dropping an extension is a heavier, more
    # surprising act than dropping an index, and another migration may come to depend on it.
